name: maven verify

on:
  workflow_dispatch

jobs:
  native:
    name: native
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - buildjet-2vcpu-ubuntu-2204-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: temurin
          cache: 'maven'
      - name: Test with Maven
        run: mvn --errors --batch-mode verify

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Test with Maven
        run: docker run --tty -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven i386/maven:ibmjava linux32 mvn --errors --batch-mode clean test
